import test from 'node:test';import assert from 'node:assert/strict';
import {createAccountPreview,normalizePhone,validateProfile,avatarFileError,passwordIssues,verifyPreviewPassword} from '../lib/scanner-account-preview.ts';
const init=()=>{const m=new Map(),storage={getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)};let time=Date.now();const actor={userId:'preview-minhanh',shiftStarted:true,expiresAt:time+3600000};return {m,storage,actor,service:createAccountPreview(storage,()=>actor,()=>time),advance:t=>time+=t};};
test('nickname phone avatar password validation',()=>{assert.equal(normalizePhone('+84 912 345 678'),'0912345678');assert.equal(validateProfile('  Minh Anh  ','0912345678').nickname,'');for(const v of ['<script>','a'.repeat(41)])assert.ok(validateProfile(v,'bad').nickname);assert.ok(avatarFileError({type:'image/svg+xml',size:10}));assert.ok(avatarFileError({type:'image/png',size:2097153}));assert.equal(avatarFileError({type:'image/webp',size:100}), '');assert.ok(passwordIssues('old','weak','wrong').next);assert.ok(passwordIssues('NewScanner@2026','NewScanner@2026','NewScanner@2026').next);});
test('profile is allowlisted; phone requires challenge before atomic save',async()=>{const {service:s}=init();await assert.rejects(s.save(' QA ','0912345678',0,'normal'),/xác minh/);await s.requestPhone('0912345678','normal');await assert.rejects(s.verifyPhone('0912345678','000000','normal'),/không đúng/);await s.verifyPhone('0912345678','123456','normal');const p=await s.save(' QA ','0912345678',0,'normal');assert.equal(p.nickname,'QA');assert.equal(p.officialName,'Minh Anh');assert.equal(p.username,'minhanh');await assert.rejects(s.save('Other',p.phone,0,'normal'),/thay đổi/);});
test('expired/duplicate/mismatched OTP cannot update identifier',async()=>{const {service:s,advance}=init();await assert.rejects(s.requestPhone('0900000001','normal'),/sử dụng/);await s.requestPhone('0912345678','normal');await assert.rejects(s.verifyPhone('0912345679','123456','normal'));advance(120001);await assert.rejects(s.verifyPhone('0912345678','123456','normal'),/hết hạn/);assert.equal(s.read().phone,'0900000000');});
test('OTP attempts exhausted, verified proof consumed, error retains profile',async()=>{const {service:s}=init();await s.requestPhone('0912345678','normal');for(let i=0;i<5;i++)await assert.rejects(s.verifyPhone('0912345678','111111','normal'));await assert.rejects(s.verifyPhone('0912345678','123456','normal'),/vượt/);await assert.rejects(s.save('QA','0900000000',0,'error'));assert.equal(s.read().nickname,'');});
test('password change validates current, hashes secret, invalidates session',async()=>{const {service:s,storage,m}=init();storage.setItem('hoanam-scanner-preview-session-v1','{}');await assert.rejects(s.password('wrong','NewScanner@2026','NewScanner@2026','normal'),/hiện tại/);await s.password('Scanner@2026','NewScanner@2026','NewScanner@2026','normal');assert.equal(await verifyPreviewPassword(storage,'Scanner@2026'),false);assert.equal(await verifyPreviewPassword(storage,'NewScanner@2026'),true);assert.equal(storage.getItem('hoanam-scanner-preview-session-v1'),null);assert.ok(!JSON.stringify([...m]).includes('NewScanner@2026'));});
test('avatar upload failure keeps old value; no mutation for expired session',async()=>{const {service:s,actor}=init();const img='data:image/jpeg;base64,/9j/';const saved=await s.avatar(img,0,'normal',()=>{});await assert.rejects(s.avatar('data:image/jpeg;base64,AAAA',saved.revision,'error',()=>{}));assert.equal(s.read().avatar,img);actor.expiresAt=0;assert.throws(()=>s.read(),/hết hạn/);await assert.rejects(s.save('new','0900000000',1,'normal'),/hết hạn/);});
