'use client';
import {useRef,useState} from 'react';
import {agencyAddress,createAgencyFixtures} from '@/lib/agency-demo';
const recipients=createAgencyFixtures().filter(a=>a.active);
const groups:Record<string,string>={'Đại lý':'agency','Nhà phân phối':'distributor','Khách công trường':'project','Khách lẻ':'retail'};
export type OutboundFields={name:string;group:string;recipient:string;phone:string;address:string;target:string;note:string};
export function outboundErrors(d:OutboundFields){return {name:d.name.trim()?'':'Nhập tên phiếu.',recipient:d.recipient.trim()?'':'Chọn hoặc nhập người nhận.',phone:/^0\d{9}$/.test(d.phone)?'':'Số điện thoại phải có 10 chữ số, bắt đầu bằng 0.',address:d.address.trim()?'':'Nhập địa chỉ giao hàng.',target:Number.isSafeInteger(Number(d.target))&&Number(d.target)>=1&&Number(d.target)<=99999?'':'Số lượng phải là số nguyên từ 1 đến 99.999.'};}
export default function ScannerOutbound({draft,update,onScan,disabled,manual}:{draft:OutboundFields;update:(values:Partial<OutboundFields>)=>void;onScan:()=>void;disabled:boolean;manual:boolean}){
 const [step,setStep]=useState(1),[search,setSearch]=useState(''),[errors,setErrors]=useState<Record<string,string>>({});const dialog=useRef<HTMLDialogElement>(null);
 const results=recipients.filter(a=>a.type===groups[draft.group]&&`${a.code} ${a.name} ${a.phone}`.toLocaleLowerCase('vi').includes(search.toLocaleLowerCase('vi')));
 const validate=(all:boolean)=>{const err=outboundErrors(draft);const keys=all?Object.keys(err):['name','recipient','phone','address'];const first=keys.find(k=>err[k as keyof typeof err]);setErrors(err);if(first){setStep(first==='target'?2:1);setTimeout(()=>document.getElementById('so-'+first)?.focus(),0);return false;}return true;};
 const field=(key:keyof OutboundFields,label:string,type='text')=><label className="sc-field" htmlFor={'so-'+key}><span>{label}</span>{key==='address'||key==='note'?<textarea id={'so-'+key} aria-label={label} value={draft[key]} disabled={disabled} readOnly={!manual&&key==='address'} onChange={e=>update({[key]:e.target.value})} aria-invalid={!!errors[key]} aria-describedby={errors[key]?'so-error-'+key:undefined}/>:<input id={'so-'+key} aria-label={label} value={draft[key]} type={type} inputMode={type==='tel'?'tel':type==='number'?'numeric':undefined} min={type==='number'?1:undefined} max={type==='number'?99999:undefined} step={type==='number'?1:undefined} disabled={disabled} readOnly={!manual&&['recipient','phone'].includes(key)} onChange={e=>update({[key]:e.target.value})} aria-invalid={!!errors[key]} aria-describedby={errors[key]?'so-error-'+key:undefined}/>} {errors[key]&&<span className="so-field-error" id={'so-error-'+key}>{errors[key]}</span>}</label>;
 return <><div className="sc-stepper"><b aria-current={step===1?'step':undefined}>1 Người nhận</b><b aria-current={step===2?'step':undefined}>2 Số lượng & xác nhận</b></div>
 <form noValidate onSubmit={e=>{e.preventDefault();if(disabled)return;if(validate(step===2)){if(step===1){setStep(2);window.scrollTo({top:0,behavior:'instant'});}else onScan();}}}>
 {step===1?<section className="sc-card"><h2>Người nhận và giao hàng</h2>{field('name','Tên phiếu *')}<p>Kho thực hiện: Kho Hoa Nam</p><label className="sc-field"><span>Nhóm đối tượng *</span><select value={draft.group} disabled={disabled} onChange={e=>{update({group:e.target.value,recipient:'',phone:'',address:''});setSearch('');}}>{Object.keys(groups).map(g=><option key={g}>{g}</option>)}</select></label><button type="button" className="sc-btn secondary" disabled={disabled} onClick={()=>dialog.current?.showModal()}>Tìm người nhận trong danh mục</button>{field('recipient','Tên người nhận / đơn vị *')}{field('phone','Số điện thoại *','tel')}{field('address','Địa chỉ giao hàng *')}<p>{manual?'Bạn có quyền lập yêu cầu xuất thủ công và bổ sung thông tin giao hàng.':'Thông tin lấy từ danh mục. Liên hệ quản trị viên khi cần thay đổi.'}</p></section>:<section className="sc-card"><h2>Số lượng, ghi chú và xác nhận</h2><p><strong>{draft.recipient}</strong><br/>{draft.phone}<br/>{draft.address}</p>{field('target','Tổng số lượng cần quét *','number')}{field('note','Ghi chú')}<p>Tồn kho chỉ thay đổi sau khi phiếu được ghi sổ.</p><button type="button" className="sc-btn secondary" onClick={()=>setStep(1)}>Sửa người nhận và giao hàng</button></section>}
 <div className="sc-sticky-actions"><button type="submit" className="sc-btn" disabled={disabled}>{step===1?'Tiếp tục: số lượng':'Bắt đầu quét'}</button></div></form>
 <dialog ref={dialog} className="sc-recipient-sheet" aria-labelledby="so-picker-title"><h2 id="so-picker-title">Chọn người nhận</h2><label className="sc-field"><span>Tìm tên, mã hoặc số điện thoại</span><input autoFocus value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="so-results">{results.map(a=><button type="button" className="sc-list-card" key={a.id} aria-label={a.name} onClick={()=>{update({recipient:a.contact||a.name,phone:a.phone,address:agencyAddress(a)});setErrors({});dialog.current?.close();}}><span><strong>{a.name}</strong><small>{a.code} · {a.phone||'Chưa có số điện thoại'}</small><small>{agencyAddress(a)}</small></span></button>)}{!results.length&&<p>Không có người nhận phù hợp. Thử tên hoặc mã khác.</p>}</div><button type="button" className="sc-btn secondary" onClick={()=>{setSearch('');}}>Xóa tìm kiếm</button><button type="button" className="sc-btn secondary" onClick={()=>dialog.current?.close()}>Đóng danh mục</button></dialog></>;
}
