'use client';
/* oxlint-disable jsx-a11y/click-events-have-key-events, jsx-a11y/no-noninteractive-element-interactions -- Native dialog backdrop click is supplemental to named Close and Escape. */
import {useEffect,useRef,useState} from 'react';
import {ArrowDownToLine,ArrowUpFromLine,Wrench,ScanQrCode,ChevronRight,X,LockKeyhole} from 'lucide-react';
import type {GlobalIntent} from '@/lib/scanner-intent';
const actions=[{intent:'INBOUND',title:'Nhập kho',description:'Nhận hàng và kiểm đếm vào kho',Icon:ArrowDownToLine},{intent:'OUTBOUND',title:'Xuất kho',description:'Soạn hàng theo yêu cầu xuất',Icon:ArrowUpFromLine},{intent:'WARRANTY',title:'Bảo hành',description:'Quét máy để tra cứu hoặc tiếp nhận bảo hành',Icon:Wrench},{intent:'LOOKUP',title:'Tra cứu sản phẩm',description:'Xem tồn kho, lịch sử và bảo hành',Icon:ScanQrCode}] as const;
export default function ScannerLauncher({hasDraft,onSelect,onResume,onClose,reason}:{hasDraft:boolean;onSelect:(intent:GlobalIntent,discard:boolean)=>void;onResume:()=>void;onClose:()=>void;reason:(intent:GlobalIntent)=>string}){
 const dialog=useRef<HTMLDialogElement>(null),origin=useRef<HTMLElement|null>(null),swipe=useRef<number|null>(null);
 const [pending,setPending]=useState<GlobalIntent|null>(null);
 const latest=useRef(onClose);useEffect(()=>{latest.current=onClose;},[onClose]);
 useEffect(()=>{origin.current=document.activeElement as HTMLElement;const el=dialog.current;el?.showModal();window.history.pushState({...window.history.state,scannerLauncher:true},'',window.location.href);const close=()=>latest.current();window.addEventListener('popstate',close);const timer=window.setInterval(()=>{if(!window.history.state?.scannerLauncher)close();},100);return()=>{window.clearInterval(timer);window.removeEventListener('popstate',close);el?.close();origin.current?.focus();};},[]);
 const close=()=>{if(window.history.state?.scannerLauncher)window.history.back();else onClose();};
 const finish=(fn:()=>void)=>{const state={...window.history.state};delete state.scannerLauncher;window.history.replaceState(state,'',window.location.href);onClose();fn();};
 return <dialog ref={dialog} className="sg-sheet" aria-labelledby="sg-title" aria-describedby="sg-subtitle" onKeyDown={e=>{if(e.key!=='Tab')return;const buttons=[...e.currentTarget.querySelectorAll<HTMLButtonElement>('button:not(:disabled)')];const first=buttons[0],last=buttons.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}} onCancel={e=>{e.preventDefault();close();}} onClick={e=>{if(e.target===e.currentTarget){const r=e.currentTarget.getBoundingClientRect();if(e.clientY<r.top||e.clientX<r.left||e.clientX>r.right)close();}}}>
 <div className="sg-handle" aria-hidden="true" onPointerDown={e=>{swipe.current=e.clientY;e.currentTarget.setPointerCapture(e.pointerId);}} onPointerUp={e=>{if(swipe.current!==null&&e.clientY-swipe.current>60)close();swipe.current=null;}}><span/></div>
 <div className="sg-heading"><h2 id="sg-title">{pending?'Bạn đang có phiếu chưa hoàn tất.':'Chọn tác vụ quét'}</h2><button className="sg-close" aria-label="Đóng chọn tác vụ quét" onClick={close}><X aria-hidden="true"/></button></div>
 <p id="sg-subtitle">{pending?'Tiếp tục phiếu đang soạn hoặc xác nhận bỏ nội dung trước khi chọn tác vụ mới.':'Mã sẽ được kiểm tra theo nghiệp vụ bạn chọn.'}</p>
 {pending?<div className="sg-confirm"><button className="sc-btn" onClick={()=>finish(onResume)}>Tiếp tục phiếu hiện tại</button><button className="sc-btn secondary" disabled={!!reason(pending)} onClick={()=>finish(()=>onSelect(pending,true))}>Bỏ phiếu và bắt đầu tác vụ mới</button>{reason(pending)&&<p>{reason(pending)}</p>}<button className="sc-btn secondary" onClick={close}>Hủy</button></div>:<div className="sg-actions">{actions.map(({intent,title,description,Icon})=>{const blocked=reason(intent);return <div key={intent}><button className="sg-action" disabled={!!blocked} aria-describedby={blocked?'sg-'+intent:undefined} onClick={()=>{if(hasDraft)setPending(intent);else finish(()=>onSelect(intent,false));}}><span className="sg-icon"><Icon aria-hidden="true"/></span><span><strong>{title}</strong><small>{description}</small></span>{blocked?<LockKeyhole aria-hidden="true"/>:<ChevronRight aria-hidden="true"/>}</button>{blocked&&<p className="sg-reason" id={'sg-'+intent}>{blocked}</p>}</div>;})}</div>}
 </dialog>;
}
