'use client';
/* oxlint-disable next/no-img-element -- Local cropped data URLs need no remote image optimizer. */
import {useEffect,useRef,useState} from 'react';
import {Camera,ChevronRight,Eye,EyeOff,UserRound,ShieldCheck,BriefcaseBusiness,LifeBuoy} from 'lucide-react';
import {avatarFileError,createAccountPreview,initialProfile,normalizePhone,passwordIssues,validateProfile,type AccountProfile} from '@/lib/scanner-account-preview';
import type {useScannerAccess} from './scanner-auth';
import type {ScannerView} from '@/lib/scanner-auth';
import './scanner-account.css';

export default function ScannerAccount({access,mode,onPasswordChanged}:{access:ReturnType<typeof useScannerAccess>;mode:string;onPasswordChanged:()=>void}){
 const [service]=useState(()=>createAccountPreview(window.sessionStorage,()=>access.actor()));
 const [profile,setProfile]=useState<AccountProfile>(()=>{try{return service.read();}catch{return initialProfile();}});
 const [nickname,setNickname]=useState(profile.nickname),[phone,setPhone]=useState(profile.phone);
 const [errors,setErrors]=useState<Record<string,string>>({}),[error,setError]=useState(''),[success,setSuccess]=useState('');
 const [busy,setBusy]=useState(false);const lock=useRef(false),dirty=useRef(false),latest=useRef(access);
 const [old,setOld]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState('');
 const [show,setShow]=useState<Record<string,boolean>>({});
 const [challenge,setChallenge]=useState(false),[otp,setOtp]=useState(''),[verified,setVerified]=useState('');
 const [source,setSource]=useState<HTMLImageElement|null>(null),[preview,setPreview]=useState('');
 const [zoom,setZoom]=useState(1),[x,setX]=useState(50),[y,setY]=useState(50),[progress,setProgress]=useState(0);
 const canvas=useRef<HTMLCanvasElement>(null),picker=useRef<HTMLInputElement>(null),camera=useRef<HTMLInputElement>(null),sheet=useRef<HTMLDialogElement>(null);
 const view=access.route.view;
 const isDirty=(view==='profile-edit'&&(nickname!==profile.nickname||phone!==profile.phone))||(view==='profile-password'&&!!(old||password||confirm))||(view==='profile-avatar'&&!!source);
 useEffect(()=>{dirty.current=isDirty;latest.current=access;},[isDirty,access]);
 useEffect(()=>{
  latest.current.setLeaveGuard(()=>{if(lock.current){window.alert('Đang lưu thay đổi. Vui lòng đợi xử lý hoàn tất.');return false;}return !dirty.current||window.confirm('Bạn có thay đổi chưa lưu. Bỏ thay đổi và rời màn hình?');});
  const unload=(e:BeforeUnloadEvent)=>{if(dirty.current)e.preventDefault();};window.addEventListener('beforeunload',unload);
  return()=>{latest.current.setLeaveGuard(null);window.removeEventListener('beforeunload',unload);};
 },[]);
 useEffect(()=>{if(!source||!canvas.current)return;const c=canvas.current,ctx=c.getContext('2d');if(!ctx)return;const side=Math.min(source.naturalWidth,source.naturalHeight)/zoom;ctx.clearRect(0,0,512,512);ctx.drawImage(source,(source.naturalWidth-side)*x/100,(source.naturalHeight-side)*y/100,side,side,0,0,512,512);setPreview(c.toDataURL('image/jpeg',.88));},[source,zoom,x,y]);
 const activeMode=()=>navigator.onLine?mode:'offline';
 const run=async(fn:()=>Promise<void>)=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');setSuccess('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Không thể lưu thay đổi.');}finally{lock.current=false;setBusy(false);}};
 const go=(next:ScannerView)=>access.navigate(next);
 const cancel=()=>go('profile');
 const msg=<>{error&&<p className="sa-error" role="alert">{error}</p>}{success&&<output className="sa-success">{success}</output>}</>;
 const saveButton=(label:string)=><button className="sc-btn" disabled={busy} type="submit">{busy?'Đang lưu…':label}</button>;
 const menu=(label:string,desc:string,next:ScannerView,Icon=UserRound)=><button className="sa-menu" onClick={()=>go(next)}><Icon aria-hidden="true"/><span><strong>{label}</strong><small>{desc}</small></span><ChevronRight aria-hidden="true"/></button>;
 const avatar=<div className="sa-avatar">{profile.avatar?<img src={profile.avatar} alt="Ảnh đại diện của bạn"/>:<span aria-label="Ảnh đại diện mặc định">MA</span>}</div>;
 const readField=(label:string,value:string)=><label className="sc-field"><span>{label}</span><input value={value} readOnly aria-readonly="true"/></label>;
 async function chooseFile(file:File|undefined){if(!file)return;setError('');const issue=avatarFileError(file);if(issue){setError(issue);return;}const url=URL.createObjectURL(file);try{const image=new Image();image.src=url;await image.decode();if(image.naturalWidth>12000||image.naturalHeight>12000||image.naturalWidth*image.naturalHeight>40000000)throw new Error('Độ phân giải ảnh quá lớn. Vui lòng chọn ảnh nhỏ hơn.');setSource(image);setZoom(1);setX(50);setY(50);setProgress(0);}catch(e){setError(e instanceof Error&&e.message.includes('phân giải')?e.message:'Không thể đọc ảnh. Vui lòng chọn tệp ảnh hợp lệ.');}finally{URL.revokeObjectURL(url);}}
 if(view==='profile')return <div className="sa-page">
  <section className="sc-card sa-profile-heading"><div className="sa-avatar-wrap">{avatar}<button className="sa-avatar-edit" aria-label="Thay ảnh đại diện" onClick={()=>go('profile-avatar')}><Camera aria-hidden="true"/></button></div><h2>{profile.officialName}</h2><p>{profile.nickname||'Thêm biệt danh của bạn'}</p><span className="sc-badge">{access.session?.role}</span></section>
  <section className="sa-group"><h3>Hồ sơ cá nhân</h3>{menu('Chỉnh sửa hồ sơ','Biệt danh, số điện thoại','profile-edit')}{menu('Ảnh đại diện','Chọn ảnh và điều chỉnh khung hình','profile-avatar',Camera)}</section>
  <section className="sa-group"><h3>Công việc và quyền</h3>{menu('Thông tin công việc','Kho Hoa Nam · quyền được cấp','profile-work',BriefcaseBusiness)}</section>
  <section className="sa-group"><h3>Tài khoản và bảo mật</h3>{menu('Bảo mật tài khoản','Mật khẩu và phiên đăng nhập','profile-security',ShieldCheck)}</section>
  <section className="sa-group"><h3>Hỗ trợ và đăng xuất</h3>{menu('Hướng dẫn sử dụng','Tra cứu các bước nghiệp vụ','profile-help',LifeBuoy)}{menu('Liên hệ hỗ trợ','Hỗ trợ tài khoản và ứng dụng','profile-support',LifeBuoy)}<p className="sa-version">Hoa Nam Scanner · Phiên bản giao diện 0.1.0</p></section>
 </div>;
 if(view==='profile-work')return <section className="sc-card sa-page"><h2>Công việc và quyền</h2><p>Thông tin do quản trị viên cấp. Bạn không thể tự thay đổi.</p>{readField('Họ tên chính thức',profile.officialName)}{readField('Vai trò',access.session?.role||'')}{readField('Kho làm việc','Kho Hoa Nam')}{readField('Phạm vi dữ liệu','Kho Hoa Nam')}<h3>Phạm vi nghiệp vụ</h3><ul>{[['Nhập kho','inbound.create'],['Xuất kho','outbound.request.manual_create'],['Bảo hành','warranty.manage'],['Linh kiện','warranty.component_issue'],['NFC','physical_code.assign_rfid']].map(([label,key])=><li key={key}>{label}: {access.session?.permissions.includes(key)?'Thực hiện theo quyền':'Xem và tra cứu'}</li>)}</ul>{readField('Quyền ghi sổ',access.session?.permissions.some(p=>p==='inbound.post'||p==='outbound.post')?'Theo quyền ghi sổ được cấp':'Không có quyền')}{readField('Đăng nhập gần nhất',profile.lastLogin?new Date(profile.lastLogin).toLocaleString('vi-VN'):'Chưa có thông tin')}</section>;
 if(view==='profile-edit')return <form className="sc-card sa-page" noValidate aria-busy={busy} onSubmit={e=>{e.preventDefault();const errs=validateProfile(nickname,phone);setErrors(errs);if(errs.nickname||errs.phone){document.getElementById(errs.nickname?'sa-nickname':'sa-phone')?.focus();return;}void run(async()=>{const next=await service.save(nickname,phone,profile.revision,activeMode());setProfile(next);setNickname(next.nickname);setPhone(next.phone);dirty.current=false;setSuccess('Đã lưu hồ sơ cá nhân.');});}}>
  <h2>Chỉnh sửa hồ sơ</h2><p>Cập nhật thông tin liên hệ của bạn.</p>{readField('Họ tên chính thức',profile.officialName)}{readField('Tên đăng nhập',profile.username)}{readField('Email',profile.email)}
  <label htmlFor="sa-nickname">Biệt danh / tên hiển thị</label><input id="sa-nickname" value={nickname} disabled={busy} onChange={e=>setNickname(e.target.value)} aria-invalid={!!errors.nickname} aria-describedby="sa-nickname-help"/><small id="sa-nickname-help">Tối đa 40 ký tự; có thể để trống.</small>{errors.nickname&&<p className="sa-error">{errors.nickname}</p>}
  <label htmlFor="sa-phone">Số điện thoại</label><input id="sa-phone" type="tel" inputMode="tel" autoComplete="tel" value={phone} disabled={busy} onChange={e=>{setPhone(e.target.value);setVerified('');setChallenge(false);setOtp('');}} aria-invalid={!!errors.phone}/>{errors.phone&&<p className="sa-error">{errors.phone}</p>}
  {normalizePhone(phone)!==profile.phone&&<section className="sa-verification"><h3>Xác minh số điện thoại mới</h3><p>Số này được dùng để đăng nhập. Chỉ cập nhật sau khi xác minh.</p><button type="button" className="sc-btn secondary" disabled={busy||!!validateProfile('',phone).phone} onClick={()=>void run(async()=>{await service.requestPhone(phone,activeMode());setChallenge(true);setVerified('');setOtp('');setSuccess('Yêu cầu xác minh đã sẵn sàng. Mã có hiệu lực 2 phút, tối đa 5 lần thử.');})}>{challenge?'Yêu cầu mã mới':'Yêu cầu xác minh'}</button>{challenge&&<><label htmlFor="sa-otp">Mã xác minh</label><input id="sa-otp" inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={otp} disabled={busy} onChange={e=>setOtp(e.target.value.replace(/\D/g,''))}/><button type="button" className="sc-btn secondary" disabled={busy||otp.length!==6} onClick={()=>void run(async()=>{await service.verifyPhone(phone,otp,activeMode());setVerified(normalizePhone(phone));setOtp('');setSuccess('Số điện thoại đã được xác minh. Chọn Lưu thay đổi để cập nhật.');})}>Xác minh số điện thoại</button></>}{verified===normalizePhone(phone)&&<p>✓ Đã xác minh số mới</p>}</section>}
  {msg}<div className="sa-actions">{saveButton('Lưu thay đổi')}<button className="sc-btn secondary" disabled={busy} type="button" onClick={cancel}>Hủy</button></div>
 </form>;
 if(view==='profile-avatar')return <section className="sc-card sa-page"><h2>Ảnh đại diện</h2><p>Ảnh JPG, PNG hoặc WebP, tối đa 2 MB. Điều chỉnh ảnh vuông trước khi lưu.</p>{!source&&avatar}
  <input ref={picker} className="sa-file" type="file" accept="image/jpeg,image/png,image/webp" aria-label="Chọn ảnh từ thư viện" onChange={e=>{void chooseFile(e.target.files?.[0]);e.target.value='';}}/>
  <input ref={camera} className="sa-file" type="file" accept="image/jpeg,image/png,image/webp" capture="user" aria-label="Chụp ảnh bằng camera" onChange={e=>{void chooseFile(e.target.files?.[0]);e.target.value='';}}/>
  <button className="sc-btn secondary" disabled={busy} onClick={()=>sheet.current?.showModal()}>{source?'Chọn ảnh khác':'Thay ảnh đại diện'}</button>
  {source&&<><div className="sa-crop"><canvas ref={canvas} width={512} height={512} aria-label="Khung cắt ảnh vuông"/></div><label>Thu phóng<input type="range" min="1" max="3" step=".05" value={zoom} disabled={busy} onChange={e=>setZoom(Number(e.target.value))}/></label><label>Dịch ngang<input type="range" min="0" max="100" value={x} disabled={busy} onChange={e=>setX(Number(e.target.value))}/></label><label>Dịch dọc<input type="range" min="0" max="100" value={y} disabled={busy} onChange={e=>setY(Number(e.target.value))}/></label><p>Ảnh sau lưu · 512 × 512 px</p><img className="sa-crop-preview" src={preview||undefined} alt="Xem trước ảnh đại diện"/>{busy&&<label>Đang lưu ảnh<progress max="100" value={progress}/></label>}<button className="sc-btn" disabled={busy||!preview} onClick={()=>void run(async()=>{setProgress(0);const next=await service.avatar(preview,profile.revision,activeMode(),setProgress);setProfile(next);setSource(null);setPreview('');dirty.current=false;setSuccess('Đã cập nhật ảnh đại diện.');})}>{busy?`Đang lưu ảnh… ${progress}%`:error?'Thử lưu ảnh lại':'Lưu ảnh đại diện'}</button></>}
  {msg}<button className="sc-btn secondary" disabled={busy} onClick={cancel}>Hủy / quay lại</button>
  <dialog ref={sheet} className="sa-sheet" aria-labelledby="sa-avatar-title"><h2 id="sa-avatar-title">Chọn ảnh đại diện</h2><p>Camera hoặc thư viện chỉ mở khi bạn chọn nguồn ảnh.</p><button className="sc-btn" onClick={()=>{sheet.current?.close();camera.current?.click();}}>Chụp ảnh</button><button className="sc-btn secondary" onClick={()=>{sheet.current?.close();picker.current?.click();}}>Chọn từ thư viện</button><button className="sc-btn secondary" onClick={()=>sheet.current?.close()}>Hủy</button></dialog>
 </section>;
 if(view==='profile-security')return <section className="sc-card sa-page"><h2>Tài khoản và bảo mật</h2>{readField('Tên đăng nhập',profile.username)}{readField('Số điện thoại đăng nhập',profile.phone)}{menu('Đổi mật khẩu','Bảo vệ tài khoản bằng mật khẩu riêng','profile-password',ShieldCheck)}<h3>Phiên đăng nhập</h3><p>Đăng nhập gần nhất: {profile.lastLogin?new Date(profile.lastLogin).toLocaleString('vi-VN'):'Chưa có thông tin'}</p><p>Đổi mật khẩu sẽ kết thúc phiên trên thiết bị này. Bạn cần đăng nhập lại để tiếp tục.</p><p>Để xử lý truy cập trên thiết bị khác, liên hệ quản trị viên.</p></section>;
 if(view==='profile-password')return <form className="sc-card sa-page" noValidate aria-busy={busy} onSubmit={e=>{e.preventDefault();const errs=passwordIssues(old,password,confirm);setErrors(errs);if(Object.values(errs).some(Boolean)){document.getElementById('sa-pass-'+(errs.old?'old':errs.next?'next':'confirm'))?.focus();return;}void run(async()=>{await service.password(old,password,confirm,activeMode());setOld('');setPassword('');setConfirm('');dirty.current=false;access.setLeaveGuard(null);onPasswordChanged();});}}><h2>Đổi mật khẩu</h2><p>Dùng 12–128 ký tự, gồm chữ hoa, chữ thường, số và ký tự đặc biệt. Không dùng lại mật khẩu hiện tại.</p>{[['old','Mật khẩu hiện tại',old,setOld],['next','Mật khẩu mới',password,setPassword],['confirm','Xác nhận mật khẩu mới',confirm,setConfirm]].map(([key,label,value,setter])=>{const id=key as string;return <div key={id}><label htmlFor={'sa-pass-'+id}>{label as string}</label><div className="sa-password"><input id={'sa-pass-'+id} type={show[id]?'text':'password'} value={value as string} autoComplete={id==='old'?'current-password':'new-password'} disabled={busy} onChange={e=>(setter as (v:string)=>void)(e.target.value)} aria-invalid={!!errors[id]}/><button type="button" disabled={busy} aria-label={(show[id]?'Ẩn ':'Hiện ')+(label as string).toLowerCase()} onClick={()=>setShow({...show,[id]:!show[id]})}>{show[id]?<EyeOff/>:<Eye/>}</button></div>{errors[id]&&<p className="sa-error">{errors[id]}</p>}</div>;})}{password&&<small>{passwordIssues(old,password,password).next||'✓ Mật khẩu mới đáp ứng yêu cầu.'}</small>}{msg}<p>Phiên trên thiết bị này sẽ kết thúc sau khi đổi mật khẩu.</p>{saveButton('Đổi mật khẩu')}<button type="button" className="sc-btn secondary" disabled={busy} onClick={cancel}>Hủy</button></form>;
 if(view==='profile-help')return <section className="sc-card sa-page"><h2>Hướng dẫn sử dụng</h2>{[['Nhập kho','Lập phiếu → quét mã → kiểm tra → gửi duyệt.'],['Xuất kho','Kiểm tra người nhận → quét đủ hàng → gửi duyệt.'],['Bảo hành và linh kiện','Tiếp nhận → kiểm tra/sửa chữa → xuất linh kiện khi đủ điều kiện → trả khách.'],['Thẻ NFC','Nhận diện hiện vật → ghi thẻ → đọc lại → xác nhận liên kết.'],['Ghi sổ','Chỉ người được cấp quyền ghi sổ mới được thay đổi tồn kho.'],['Kho tạm dừng','Chỉ xem và tra cứu. Nội dung đang soạn được giữ trong lần mở này.']].map(([h,t])=><details key={h}><summary>{h}</summary><p>{t}</p></details>)}</section>;
 return <section className="sc-card sa-page"><h2>Liên hệ hỗ trợ</h2><p>Vui lòng liên hệ quản trị viên hoặc người đã cấp tài khoản tại Kho Hoa Nam.</p><p>Khi cần hỗ trợ, cung cấp tên màn hình và thời điểm gặp lỗi. Không gửi mật khẩu hoặc mã xác minh.</p><p>Hoa Nam Scanner · Phiên bản giao diện 0.1.0</p></section>;
}
